package com.ff.pojo;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.commodity_name
     *
     * @mbggenerated
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.commodity_price
     *
     * @mbggenerated
     */
    private Double commodityPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buy_user
     *
     * @mbggenerated
     */
    private String buyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buy_date
     *
     * @mbggenerated
     */
    private Date buyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_price
     *
     * @mbggenerated
     */
    private Double totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.commodity_name
     *
     * @return the value of order.commodity_name
     *
     * @mbggenerated
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.commodity_name
     *
     * @param commodityName the value for order.commodity_name
     *
     * @mbggenerated
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.commodity_price
     *
     * @return the value of order.commodity_price
     *
     * @mbggenerated
     */
    public Double getCommodityPrice() {
        return commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.commodity_price
     *
     * @param commodityPrice the value for order.commodity_price
     *
     * @mbggenerated
     */
    public void setCommodityPrice(Double commodityPrice) {
        this.commodityPrice = commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.buy_user
     *
     * @return the value of order.buy_user
     *
     * @mbggenerated
     */
    public String getBuyUser() {
        return buyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.buy_user
     *
     * @param buyUser the value for order.buy_user
     *
     * @mbggenerated
     */
    public void setBuyUser(String buyUser) {
        this.buyUser = buyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.buy_date
     *
     * @return the value of order.buy_date
     *
     * @mbggenerated
     */
    public Date getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.buy_date
     *
     * @param buyDate the value for order.buy_date
     *
     * @mbggenerated
     */
    public void setBuyDate(Date buyDate) {
        this.buyDate = buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amount
     *
     * @return the value of order.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_price
     *
     * @return the value of order.total_price
     *
     * @mbggenerated
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_price
     *
     * @param totalPrice the value for order.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
}